apiVersion: v1
kind: PersistentVolume
metadata:
  name: db2u-nfs
spec:
  mountOptions:
  - v4.2
  - context="system_u:object_r:container_file_t:s0"
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: SERVER_ADDRESS
    path: SERVER_PATH
